[project]
name = "mcausp"
version = "0.1.0"
description = "Model can audit your security policy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "psutil>=7.0.0",
    "wmi>=1.5.1",
]
